<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="wwwroot\admin\js\helpers\ckeditor\skins\bootstrapck\.temp\css\dialog.css" />
    <Content Include="wwwroot\admin\js\helpers\ckeditor\skins\bootstrapck\.temp\css\dialog_ie.css" />
    <Content Include="wwwroot\admin\js\helpers\ckeditor\skins\bootstrapck\.temp\css\dialog_ie7.css" />
    <Content Include="wwwroot\admin\js\helpers\ckeditor\skins\bootstrapck\.temp\css\dialog_ie8.css" />
    <Content Include="wwwroot\admin\js\helpers\ckeditor\skins\bootstrapck\.temp\css\dialog_iequirks.css" />
    <Content Include="wwwroot\admin\js\helpers\ckeditor\skins\bootstrapck\.temp\css\dialog_opera.css" />
    <Content Include="wwwroot\admin\js\helpers\ckeditor\skins\bootstrapck\.temp\css\editor.css" />
    <Content Include="wwwroot\admin\js\helpers\ckeditor\skins\bootstrapck\.temp\css\editor_gecko.css" />
    <Content Include="wwwroot\admin\js\helpers\ckeditor\skins\bootstrapck\.temp\css\editor_ie.css" />
    <Content Include="wwwroot\admin\js\helpers\ckeditor\skins\bootstrapck\.temp\css\editor_ie7.css" />
    <Content Include="wwwroot\admin\js\helpers\ckeditor\skins\bootstrapck\.temp\css\editor_ie8.css" />
    <Content Include="wwwroot\admin\js\helpers\ckeditor\skins\bootstrapck\.temp\css\editor_iequirks.css" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Infrastructures\KitKap.Service\KitKap.Service.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\Admin\Data\" />
    <Folder Include="Areas\Admin\Models\" />
    <Folder Include="Areas\Admin\Views\Shared\Components\_AdminLayoutHeadComponentPartial\" />
    <Folder Include="wwwroot\template\assets\images\demoes\demo35\products\zoom\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
  </ItemGroup>

</Project>
